version: '1'
services:
#mssql docker
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=KinoPlus123
      - MSSQL_PID=Developer
    ports:
      - 1435:1433
    networks:
      - kinoplusnet

  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: KinoPlus.API\Dockerfile
    environment:
      - ConnectionStrings:DefaultConnection=Server=sql,1433;Database=kinoplus_docker;User=sa;Password=KinoPlus123;TrustServerCertificate=True;ConnectRetryCount=0
    ports:
      - 8080:80
    networks:
      - kinoplusnet      
    links:
      - sql
    depends_on:
      - sql
      
networks:
  kinoplusnet:
    driver: bridge 