name: mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_rating_bar: ^4.0.1
  intl: ^0.18.0
  transparent_image: ^2.0.1
  collection: ^1.17.0
  provider: ^6.0.5
  barcode_widget: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/

  fonts:
    - family: "Albert Sans"
      fonts:
        - asset: assets/fonts/albert_sans/AlbertSans-Regular.ttf
        - asset: assets/fonts/albert_sans/AlbertSans-Medium.ttf
          weight: 500

  uses-material-design: true
